home/urls.py
from django.urls import path, include
from . import views
from django.conf import settings

urlpatterns = [
    path('hitter-report/<int:report_id>/edit', views.hitter_report_edit, name='edit hitter report'),
    path('hitter-report/<int:report_id>', views.hitter_report_view, name='hitter report'),
    path('pitcher-report/<int:report_id>', views.pitcher_report_view, name='hitter report'),
    path('hitter-report/create', views.hitter_report_add, name='add hitter report'),
    path('pitcher-report/create', views.pitcher_report_add, name='add pitcher report'),
    path('pitcher-report/<int:report_id>/edit', views.pitcher_report_edit, name='edit pitcher report'),
    path('delete/<str:report_type>/<int:report_id>', views.delete_report, name='delete report'),
    path('', views.home, name='home'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls)),
        # ... your other URL patterns ...
    )

scout/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
]

home/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.


class HitterReport(models.Model):
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    team = models.IntegerField()
    position = models.CharField(max_length=3)
    bats = models.CharField(max_length=1)
    throws = models.CharField(max_length=1)
    date = models.DateField()
    overall = models.IntegerField(validators=[MinValueValidator(20), MaxValueValidator(80)])
    fvoverall = models.IntegerField(validators=[MinValueValidator(20), MaxValueValidator(80)])
    summary = models.TextField()
class HitterStats(models.Model):
    player = models.ForeignKey(HitterReport, on_delete=models.CASCADE)
    stat = models.CharField(max_length=15)
    value = models.IntegerField(validators=[MinValueValidator(20), MaxValueValidator(80)])
    futurevalue = models.IntegerField(validators=[MinValueValidator(20), MaxValueValidator(80)])
    comment = models.TextField(null=True, blank=True)
class PitcherReport(models.Model):
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    team = models.IntegerField()
    position = models.CharField(max_length=3)
    throws = models.CharField(max_length=1)
    date = models.DateField()
    summary = models.TextField()
    overall = models.IntegerField(validators=[MinValueValidator(20), MaxValueValidator(80)])
    fvoverall = models.IntegerField(validators=[MinValueValidator(20), MaxValueValidator(80)])

class PitcherStats(models.Model):
    player = models.ForeignKey(PitcherReport, on_delete=models.CASCADE)
    pitch_type = models.CharField(max_length=15)
    velo_low = models.IntegerField()
    velo_high = models.IntegerField()
    value = models.IntegerField(validators=[MinValueValidator(20), MaxValueValidator(80)])
    futurevalue = models.IntegerField(validators=[MinValueValidator(20), MaxValueValidator(80)])
    comment = models.TextField(null=True, blank=True)

home/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from home.models import HitterReport, HitterStats, PitcherReport, PitcherStats
import requests
from django.utils.dateparse import parse_date
from .utils.mlb_team_utils import get_teams
from .utils.player_utils import get_hitter_stats, get_positions, get_handedness, get_pitch_types, get_pitcher_positions
from .utils.mlb_news_utils import get_mlb_news
from urllib.parse import urlparse
from .utils.form_validation import validate_player_info, validate_hitter_stats, validate_pitcher_stats

# Create your views here.
def home(request):
    hitterReports = HitterReport.objects.all()
    pitcherReports = PitcherReport.objects.all()
    news = get_mlb_news()[0:4]
    template = loader.get_template('home.html')
    context = {
        'hitter_reports': hitterReports,
        'pitcher_reports': pitcherReports,
        'news': news
    }
    return HttpResponse(template.render(context, request))

def hitter_report_add(request):
    if request.method == 'POST':
        data = request.POST
        errors = validate_player_info(data, 'hitter')
        errors.extend(validate_hitter_stats(data))
        if len(errors) > 0:
            teams=get_teams()
            positions = get_positions()
            handedness = get_handedness()
            hitter_stats = get_hitter_stats()
            template = loader.get_template('add_hitter_report.html')
            context = {
                "teams": teams,
                "positions": positions,
                "handedness": handedness,
                "hitter_stats": hitter_stats,
                "errors": errors,
            }
            return HttpResponse(template.render(context, request))
        else:
            date_str = request.POST.get('date')
            date = parse_date(date_str)
            report = HitterReport(
                firstname=data.get('firstname'),
                lastname=data.get('lastname'),
                position=data.get('position'),
                bats=data.get('bats'),
                throws=data.get('throws'),
                date=date,
                summary=data.get('statement'),
                team=data.get('team'),
                overall=data.get('Overall'),
                fvoverall=data.get('fvOverall')
            )
            report.save()
            stats = get_hitter_stats()
            for stat in stats:
                stat_obj = HitterStats(
                    player=report,
                    stat=stat,
                    value=data.get(stat),
                    futurevalue=data.get('fv'+stat),
                    comment=data.get('comment'+stat)
                )
                stat_obj.save()
            return redirect('home')
    elif request.method == 'GET':
        teams=get_teams()
        positions = get_positions()
        handedness = get_handedness()
        hitter_stats = get_hitter_stats()
        template = loader.get_template('add_hitter_report.html')
        context = {
            "teams": teams,
            "positions": positions,
            "handedness": handedness,
            "hitter_stats": hitter_stats,
        }
        return HttpResponse(template.render(context, request))

def hitter_report_view(request, report_id):
    report = HitterReport.objects.get(id=report_id)
    template = loader.get_template('view_hitter_report.html')
    return HttpResponse(template.render({'report': report}, request))

def hitter_report_edit(request, report_id):
    report = HitterReport.objects.get(id=report_id)
    if request.method == "GET":
        teams=get_teams()
        positions = get_positions()
        handedness = get_handedness()
        hitter_stats = get_hitter_stats()
        context = {
            "teams": teams,
            "positions": positions,
            "handedness": handedness,
            "hitter_stats": hitter_stats,
            "report": report
        }
        template = loader.get_template('edit_hitter_report.html')
        return HttpResponse(template.render(context, request))
    elif request.method == "POST":
        data = request.POST
        errors = validate_player_info(data, 'hitter')
        errors.extend(validate_hitter_stats(data))
        if len(errors) > 0:
            teams=get_teams()
            positions = get_positions()
            handedness = get_handedness()
            hitter_stats = get_hitter_stats()
            template = loader.get_template('edit_hitter_report.html')
            context = {
                "teams": teams,
                "positions": positions,
                "handedness": handedness,
                "hitter_stats": hitter_stats,
                "errors": errors,
                "report": report,
            }
            return HttpResponse(template.render(context, request))
        else:
            date_str = request.POST.get('date')
            date = parse_date(date_str)
            report = HitterReport.objects.get(id=report_id)
            report.firstname=data.get('firstname')
            report.lastname=data.get('lastname')
            report.position=data.get('position')
            report.bats=data.get('bats')
            report.throws=data.get('throws')
            report.date=date
            report.summary=data.get('statement')
            report.team=data.get('team')
            report.overall=data.get('Overall')
            report.fvoverall=data.get('fvOverall')
            report.save()
            stats = get_hitter_stats()
            for stat in stats:
                stat_obj = report.hitterstats_set.get(stat=stat)
                stat_obj.value=data.get(stat)
                stat_obj.futurevalue=data.get('fv'+stat)
                stat_obj.comment=data.get('comment'+stat)
                stat_obj.save()
            return redirect('/hitter-report/'+str(report_id))

def pitcher_report_add(request):
    if request.method == "POST":
        data = request.POST
        date_str = request.POST.get('date')
        errors = validate_player_info(data, 'pitcher')
        print(errors)
        errors.extend(validate_pitcher_stats(data))
        if len(errors) > 0:
            context = {
                "teams": get_teams(),
                "positions": get_pitcher_positions(),
                "handedness": get_handedness(),
                "pitch_ids": range(1, 5),
                "pitch_types": get_pitch_types(),
                "errors": errors,
            }
            return render(request, 'add_pitcher_report.html', context)
        else:
            date = parse_date(date_str)
            report = PitcherReport(
                firstname=data.get('firstname'),
                lastname=data.get('lastname'),
                position=data.get('position'),
                throws=data.get('throws'),
                date=date,
                summary=data.get('statement'),
                team=data.get('team'),
                overall=data.get('Overall'),
                fvoverall=data.get('fvOverall')
            )
            report.save()
            for i in range(1, 5):
                pitch_type = data.get('pitch'+str(i))
                velo_low = data.get('pitch'+str(i)+'-velo-low')
                velo_high = data.get('pitch'+str(i)+'-velo-high')
                value = data.get('pitch'+str(i)+'-grade')
                comment = data.get('pitch'+str(i)+'-comment')
                fv = data.get('pitch'+str(i)+'-fv')
                pitch_obj = PitcherStats(
                    player=report,
                    pitch_type=pitch_type,
                    velo_low=velo_low,
                    velo_high=velo_high,
                    value=value,
                    futurevalue=fv,
                    comment=comment
                )
                pitch_obj.save()
            return redirect('home')
    if request.method == "GET":
        teams=get_teams()
        positions = get_pitcher_positions()
        handedness = get_handedness()
        template = loader.get_template('add_pitcher_report.html')
        context = {
            "teams": teams,
            "positions": positions,
            "handedness": handedness,
            "pitch_ids": range(1, 5),
            "pitch_types": get_pitch_types()
        }
        return HttpResponse(template.render(context, request))

def pitcher_report_view(request, report_id):
    report = PitcherReport.objects.get(id=report_id)
    template = loader.get_template('view_pitcher_report.html')
    return HttpResponse(template.render({'report': report}, request))

def pitcher_report_edit(request, report_id):
    if request.method == "GET":
        report = PitcherReport.objects.get(id=report_id)
        context = {
            "teams": get_teams(),
            "positions": get_pitcher_positions(),
            "handedness": get_handedness(),
            "pitch_ids": range(1, 5),
            "pitch_types": get_pitch_types(),
            "report": report
        }
        template = loader.get_template('edit_pitcher_report.html')
        return HttpResponse(template.render(context, request))
    elif request.method == "POST":
        data = request.POST
        errors = validate_player_info(data, 'pitcher')
        errors.extend(validate_pitcher_stats(data))
        if len(errors) > 0:
            context = {
                "teams": get_teams(),
                "positions": get_pitcher_positions(),
                "handedness": get_handedness(),
                "pitch_ids": range(1, 5),
                "pitch_types": get_pitch_types(),
                "errors": errors,
            }
            return render(request, 'edit_pitcher_report.html', context)
        else:
            date_str = request.POST.get('date')
            date = parse_date(date_str)
            report = PitcherReport.objects.get(id=report_id)
            report.firstname=data.get('firstname')
            report.lastname=data.get('lastname')

home/templates/add_hitter_report.html
{% extends "master.html" %}
{% block title %} Create Hitter Report | Scout {% endblock %}
{% block content %}
{% include 'error_box.html' with errors=errors%}
<div class="d-flex justify-content-between mt-2">
    <h2>Create Hitter Report</h2>
    <a href="/" class="btn scout-btn">Back to Reports</a>
</div>
{% include "hitter_form.html" %}
{% endblock content %}

home/templates/add_pitcher_report.html
{% extends "master.html" %}
{% load team_id_to_code %}
{% load get_stat_by_name %}
{% load order_by_custom_stat %}

{% block title %} Add Pitcher Report | Scout {% endblock %}

{% block content %}
{% include 'error_box.html' with errors=errors%}
<div class="d-flex justify-content-between mt-2">
    <h2>Create Pitcher Report</h2>
    <a href="/" class="btn scout-btn">Back to Reports</a>
</div>
{% include "pitcher_form.html" %}
{% endblock %}

home/templates/delete_report.html
{% extends "master.html" %}
{% block title %}
Delete {{ type }} {{ report.firstname }} {{ report.lastname}}
{% endblock %}
{% block content %}
<div class='d-flex justify-content-center align-items-center' style="height: 70vh">
<div class='card'>
    <div class='card-header scout-title'>
        <h5 class='card-title'>
            Delete {{ type|title }} {{ report.firstname }} {{report.lastname}}
        </h5>
    </div>
    <div class='card-body'>
        <p class='card-text scout-title'>By deleting this record, it will be unrecoverable.</p>
    </div>
    <div class='card-footer'>
        <form method='post'>
        {% csrf_token %}
        <button class='btn btn-danger' name='action' value='delete'>Delete</button>
        <button class='btn btn-secondary' name='action' value='cancel'>Cancel</button>
        <input type='hidden' name='source' value={{ source }}>
        </form>
    </div>
</div>
</div>
{% endblock %}

home/templates/edit_pitcher_report.html
{% extends "master.html" %}
{% block title %} Edit Pitcher Report | Scout {% endblock %}
{% block content %}
<div class="d-flex justify-content-between mt-2">
    <h2>Edit Pitcher Report</h2>
    <a href="/" class="btn scout-btn">Back to Reports</a>
</div>
{% include 'pitcher_form.html' with report=report%}
{% endblock %}

home/templates/hitter_form.html
{%load get_stat_by_name%}
{%load get_overall_stat%}

<form method='post'>
    {% csrf_token %}
    {% include "player_info_form.html" with form_for="hitter" %}
    <div class="row my-2">
        <div class="card px-0">
            <div class="card-body">
            {% for stat in hitter_stats%}
            {% if report is not None %}
            {% with report.hitterstats_set.all|get_stat_by_name:stat as stat_report%}
            {% include "stat_control_box.html" with stat=stat stat_report=stat_report%}
            {%endwith%}
            {% else %}
            {% include "stat_control_box.html" with stat=stat%}
            {% endif %}
            {%endfor%}
            <hr class="card-divider" />
            {% if report is not None %}
            {% with report|get_overall_stat as stat_report%}
            {% include "stat_control_box.html" with stat='Overall' stat_report=stat_report%}
            {%endwith%}
            {% else %}
            {% include "stat_control_box.html" with stat='Overall'%}
            {% endif %}
        </div>
        <div class="card-footer">
            <button type="submit" class="btn scout-btn">Submit</button>
        </div>
        </div>
        </div>
    </div>
</form>

home/templates/home.html
{% extends "master.html" %}
{% load order_by_custom_stat %}
{% load get_pitch_by_name %}

{% block title %}
  Scout
{% endblock %}


{% block content %}
    <div class="d-flex mt-2 justify-content-between">
        <h2>Hitter Reports</h2>
        <a class="btn scout-btn" href="/hitter-report/create">Create New Report</a>
    </div>
    <table class="table table-borderless hitter-table mt-2">
      <thead>
        <tr>
          <th width="10%">Date</th>
          <th width="1%">Org</th>
          <th width="2%">Pos</th>
          <th>Player</th>
          <th width="5%">Hit</th>
          <th width="5%">Pow</th>
          <th width="5%">Run</th>
          <th width="5%">Field</th>
          <th width="5%">Thr</th>
          <th width="5%">OVR</th>
          <th width="8%">Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for report in hitter_reports %}
        <tr>
          <td>{{report.date}}</td>
          <td><img src="
            https://www.mlbstatic.com/team-logos/{{report.team}}.svg" /></td>
          <td>{{report.position}}</td>
          <td><a href="/hitter-report/{{report.id}}" class="link-primary">{{report.lastname}}, {{report.firstname}}</a></td>
          {% with report.hitterstats_set.all|order_by_custom_stat as stats %}
          {% for stat in stats %}
            <td>{{ stat.value }}</td>
          {% endfor %}
        {% endwith %}
        <td>{{report.overall}}</td>
        <td>
          <div class='d-flex justify-content-between'>
          <a href="/hitter-report/{{report.id}}/edit" class="link-primary pr-3">Edit</a>
          <a href="/delete/hitter/{{report.id}}" class="link-danger">Delete</a>
          </div>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <div class="d-flex mt-2 justify-content-between">
      <h2>Pitcher Reports</h2>
      <a class="btn scout-btn" href="/pitcher-report/create">Create New Report</a>
    </div>
    <table class="table table-borderless hitter-table mt-2">
      <thead>
        <tr>
          <th width="10%">Date</th>
          <th width="1%">Org</th>
          <th width="2%">Pos</th>
          <th>Player</th>
          <th width="5%">FB</th>
          <th width="6%">FB Velo</th>
          <th width="5%">OVR</th>
          <th width="8%">Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for report in pitcher_reports %}
        <tr>
          <td>{{report.date}}</td>
          <td><img src="
            https://www.mlbstatic.com/team-logos/{{report.team}}.svg" /></td>
          <td>{{report.position}}</td>
          <td><a href="/pitcher-report/{{report.id}}" class="link-primary">{{report.lastname}}, {{report.firstname}}</a></td>
          {% with report.pitcherstats_set.all|get_pitch_by_name:'Fastball' as pitch%}
          {% if pitch is None%}
          <td>N/A</td>
          <td>N/A</td>
          {% else %}
          <td>{{pitch.value}}</td>
          <td>{{pitch.velo_low}}-{{pitch.velo_high}}</td>
          {% endif %}
          {% endwith %}
          <td>
            {{report.overall}}
          </td>
          <td>
            <div class='d-flex justify-content-between'>
              <a href="/pitcher-report/{{report.id}}/edit" class="link-primary pr-3">Edit</a>
              <a href="/delete/pitcher/{{report.id}}" class="link-danger">Delete</a>
            </div>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <div class="d-flex mt-2 justify-content-between">
      <h2>MLB News</h2>
    </div>
      <div class='row'>
      {% for item in news%}
      <div class='col-md-3'>
        <div class="card">
          <img src="{{item.image}}" class="card-img-top" alt="...">
          <div class="card-body">
            <a href="{{item.link}}"><h6 class="card-title">{{item.title}}</h6></a>
            <p class='scout-title'>{{item.author}} - {{item.pubDate}}</p>
          </div>
        </div>
      </div>
      {%endfor%}
      </div>
    </div>

{% endblock %}

home/templates/master.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %}{% endblock %}</title>
  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
  <link rel="stylesheet" href="{% static 'styles.css' %}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;600&display=swap" rel="stylesheet">
</head>
<body>

<nav class="navbar" id="scout-navbar">
    <div class="container">
        <img src="{% static 'scout-logo.png'%}" alt="Bootstrap" width="auto" height="30px" />
    </div>
</nav>
<div class="container">
{% block content %}
{% endblock %}
</div>
</div>

</body>
</html>

home/templates/pitch_control_box.html
<div class='col-md-2'>
    <label for='pitcher-type' class='form-label scout-form-label'>Pitch {{id}}</label>
    <select name='pitch{{id}}' class='form-select'>
      <option value=''>...</option>
      {% for type in pitch_types %}
      <option value={{type}} {% if stat_report and stat_report.pitch_type == type%}selected{% endif %}>{{type}}</option>
      {% endfor %}
    </select>
    {% comment %} <input type='text' name='pitch{{id}}' id='pitch{{id}}' class='form-control' /> {% endcomment %}
</div>
<div class='col-md-1'>
    <label for='pitch{{id}}-velo-low' class='form-label  scout-form-label'>Velo (Low)</label>
    <input type='text' name='pitch{{id}}-velo-low' id='velo-low' class='form-control' value={{stat_report.velo_low}}>
</div>
<div class='col-md-1'>
    <label for='velo-high' class='form-label scout-form-label'>Velo (High)</label>
    <input type='text' name='pitch{{id}}-velo-high' id='velo-high' class='form-control' value={{stat_report.velo_high}}>
</div>
<div class="col-md-2">
    <label for="pitch{{id}}-grade" class="form-label scout-form-label">
      Grade
    </label>
    <select class="form-select" id="pitch{{id}}-grade" name="pitch{{id}}-grade">
      <option {% if stat_report is None %} selected {% endif %}>...</option>
      <option value="20" {% if stat_report and stat_report.value == 20%}selected{%endif%}>20</option>
      <option value="30" {% if stat_report and stat_report.value == 30%}selected{%endif%}>30</option>
      <option value="40" {% if stat_report and stat_report.value == 40%}selected{%endif%}>40</option>
      <option value="50" {% if stat_report and stat_report.value == 50%}selected{%endif%}>50</option>
      <option value="60" {% if stat_report and stat_report.value == 60%}selected{%endif%}>60</option>
      <option value="70" {% if stat_report and stat_report.value == 70%}selected{%endif%}>70</option>
      <option value="80" {% if stat_report and stat_report.value == 80%}selected{%endif%}>80</option>
    </select>
</div>
<div class="col-md-2">
    <label for="fv-{{stat}}" class="form-label scout-form-label">
      FV
    </label>
    <select class="form-select" id="pitch{{id}}-fv" name="pitch{{id}}-fv">
      <option {% if stat_report is None %} selected {% endif %}>...</option>
      <option value="20" {% if stat_report and stat_report.futurevalue == 20%}selected{%endif%}>20</option>
      <option value="30" {% if stat_report and stat_report.futurevalue == 30%}selected{%endif%}>30</option>
      <option value="40" {% if stat_report and stat_report.futurevalue == 40%}selected{%endif%}>40</option>
      <option value="50" {% if stat_report and stat_report.futurevalue == 50%}selected{%endif%}>50</option>
      <option value="60" {% if stat_report and stat_report.futurevalue == 60%}selected{%endif%}>60</option>
      <option value="70" {% if stat_report and stat_report.futurevalue == 70%}selected{%endif%}>70</option>
      <option value="80" {% if stat_report and stat_report.futurevalue == 80%}selected{%endif%}>80</option>
    </select>
</div>
<div class="col-md-4">
    <label for="comment-{{stat}}" class="form-label scout-form-label">
      Comments
    </label>
    <input type="text" class="form-control" id="pitch{{id}}-comment" name="pitch{{id}}-comment" {% if stat_report and stat_report.comment %}value={{stat_report.comment}}{%endif%} />
</div>

home/templates/pitcher_form.html
{%load get_stat_by_name%}
{%load get_overall_stat%}

<form method='post'>
    {% csrf_token %}
    {% include 'player_info_form.html' with form_for="pitcher" %}
    <div class='row my-2'>
        <div class='card px-0'>
            <div class='card-body'>
                {% if report is None %}
                {% for id in pitch_ids %}
                <div class='row {% if id == 1 %} mt-2 mb-1 {% elif id == 4 %} mt-1 mb-2 {% else %} my-1 {% endif %}'>
                    {% include "pitch_control_box.html" with id=id pitch_types=pitch_types%}
                </div>
                {% endfor %}
                {% else %}
                {% with report.pitcherstats_set.all as pitches%}
                {% for pitch in pitches %}
                <div class='row {% if forloop.first %} mt-2 mb-1 {% elif forloop.last %} mt-1 mb-2 {% else %} my-1 {% endif %}'>
                    {% include "pitch_control_box.html" with pitch_types=pitch_types stat_report=pitch id=forloop.counter%}
                </div>
                {% endfor %}
                {% endwith %}
                {% endif %}

                <hr />
                {% if report is None %}
                {% include "stat_control_box.html" with stat="Overall" %}
                {% else %}
                {% with report|get_overall_stat as stat_report %}
                {% include "stat_control_box.html" with stat="Overall" stat_report=stat_report %}
                {% endwith %}
                {% endif %}
            </div>
            <div class='card-footer'>
                <button type='submit' class='btn scout-btn'>Submit</button>
            </div>
        </div>
    </div>
</form>

home/templates/player_info.html
{% load team_id_to_code %}

<div class='card'>
    <div class='card-header'>
        <div class='d-flex'>
            <img src="
            https://www.mlbstatic.com/team-logos/{{report.team}}.svg" class='team-logo' />
            <div class='d-flex align-items-end flex-grow-1'>
                <div class='d-flex flex-column mx-2 flex-grow-1'>
                    <h5 class='scout-subtitle'>Player</h5>
                    <h3 class='scout-title'>{{report.lastname}}, {{report.firstname}}</h3>
                </div>
                <div class='d-flex flex-column mx-2'>
                    <h5 class='scout-subtitle'>Date</h5>
                    <h5 class='scout-title'>{{report.date}}</h5>
                </div>
                <div class='d-flex flex-column mx-2'>
                    <h5 class='scout-subtitle'>Team</h5>
                    <h5 class='scout-title'>{{report.team | team_id_to_code}}</h5>
                </div>
                <div class='d-flex flex-column mx-2'>
                    <h5 class='scout-subtitle'>Position</h5>
                    <h5 class='scout-title'>{{report.position}}</h5>
                </div>
                {% if type == 'hitter' %}
                <div class='d-flex flex-column mx-2'>
                    <h5 class='scout-subtitle'>Bat</h5>
                    <h5 class='scout-title'>{{report.bats}}</h5>
                </div>
                {% endif %}
                <div class='d-flex flex-column mx-2'>
                    <h5 class='scout-subtitle'>Thr</h5>
                    <h5 class='scout-title'>{{report.throws}}</h5>
                </div>
            </div>
        </div>
    </div>
    <div class='card-body'>
        <div class='row'>
            <div class='col-md-2'>
                <h5 class='scout-title'>Overall</h5>
                <div class='stat-box'>
                <p>{{report.overall}}</p>
                </div>
            </div>
            <div class='col-md-2'>
                <h5 class='scout-title'>Future</h5>
                <div class='stat-box'>
                <p>{{report.fvoverall}}</p>
                </div>
            </div>
            <div class='col-md-8'>
                <h5 class='scout-title'>
                    Declarative Statement
                </h5>
                <p class='scout-text'>{{report.summary}}</p>
            </div>
        </div>
    </div>
</div>

home/templates/view_pitcher_report.html
{% extends "master.html" %}
{% load team_id_to_code %}
{% load get_stat_by_name %}
{% load order_by_custom_stat %}

{% block title %} {{report.name}} | Scout {% endblock %}
{% block content %}
<div class='d-flex justify-content-between my-2'>
    <h2>View Hitting Report</h2>
    <div>
        <a href="/hitter-report/create" class='btn scout-btn mr-2'>Create New Report</a>
        <a href="/" class='btn scout-btn'>Back to Reports</a>
    </div>
</div>
{% include 'player_info.html' with report=report type='pitcher' %}
<table class='table table-borderless hitter-table mt-2'>
    <thead>
        <tr>
            <th>Grade/FV</th>
            <th>Pitch Type</th>
            <th>Velo</th>
            <th width='80%'>Comments</th>
        </tr>
    </thead>
    <tbody>
        {% with report.pitcherstats_set.all as pitches%}
        {% for pitch in pitches %}
        <tr>
            <td>
                <div class='d-flex justify-content-between'>
                    <div class='stat-box' style="color: #fff; font-weight: bold; width: 2.2em">
                    {{pitch.value}}
                    </div>
                    <div class='stat-box' style="color: #fff; font-weight: bold; width: 2.2em">
                        {{pitch.futurevalue}}
                    </div>
                </div>
            </td>
            <td>{{pitch.pitch_type}}</td>
            <td>{{pitch.velo_low}}-{{pitch.velo_high}}</td>
            <td>{{pitch.comment}}</td>
        </tr>
        {% endfor %}
        {% endwith %}
    </tbody>
</table>
<div class='d-flex justify-content-end'>
    <a href="/delete/pitcher/{{report.id}}" class='btn btn-danger'>
        Delete Report
    </a>
</div>
{% endblock %}